name: 'Coolify Deploy Bot'
description: 'Comment PRs with Coolify deployment status + URLs'
branding:
  icon: 'rocket'
  color: 'blue'

inputs:
  coolify_base_url:
    description: 'Base URL of your Coolify instance (e.g., https://coolify.yourdomain.com)'
    required: true
  coolify_api_token:
    description: 'Coolify API token (created in Keys & Tokens → API tokens)'
    required: true
  coolify_app_uuid:
    description: 'UUID of the application in Coolify'
    required: true
  github_token:
    description: 'GitHub token for posting comments (defaults to GITHUB_TOKEN)'
    required: false
  poll_interval:
    description: 'Polling interval in seconds (default: 3). Adjust based on your build times - faster builds can use 3s, slower builds may prefer 5-10s'
    required: false
    default: '3'
  timeout_minutes:
    description: 'Timeout in minutes for waiting for deployment completion (default: 30)'
    required: false
    default: '30'

outputs:
  found:
    description: 'Whether a deployment was found for this commit'
  status:
    description: 'Deployment status (finished, failed, in_progress, etc.)'
  url:
    description: 'Deployed application URL (fqdn)'
  log_link:
    description: 'Link to deployment logs in Coolify'

runs:
  using: 'node20'
  main: 'dist/index.js'

